language: java

matrix:
  include:
    - os: linux
      dist: bionic
      jdk: oraclejdk11
      addons:
        apt:
          packages:
            - libgtk-3-dev
    - os: osx
      osx_image: xcode11
      jdk: oraclejdk11

script:
  - ./gradlew build
